name: Prepare Environment

inputs:
    NAME:
        required: true
        type: string
    OPENMDAO_PIXI_ENVIRONMENT:
        required: true
        type: string
    OPENMDAO_INSTALL_FROM:
        required: true
        type: string
    OPENMDAO:
        required: true
        type: string
    SNOPT:
        required: true
        type: string
    DYMOS:
        required: true
        type: string
    PYOPTSPARSE:
        required: true
        type: string
    SSH_PRIVATE_KEY:
        required: true
    SSH_KNOWN_HOSTS:
        required: true
    SNOPT_LOCATION_77:
        required: true

    # Deprecate
    PY:
        required: true
        type: string
    NUMPY:
        required: true
        type: string
    SCIPY:
        required: true
        type: string

runs:
  using: "composite"
  steps:
    - name: Display run details
      shell: bash -l {0}
      run: |
        echo "============================================================="
        echo "Run #${GITHUB_RUN_NUMBER}"
        echo "Run ID: ${GITHUB_RUN_ID}"
        echo "Testing: ${GITHUB_REPOSITORY}"
        echo "Triggered by: ${GITHUB_EVENT_NAME}"
        echo "Initiated by: ${GITHUB_ACTOR}"
        echo "============================================================="

    - name: Checkout Aviary
      uses: actions/checkout@v6

    - name: Create SSH key
      shell: bash -l {0}
      env:
        SSH_PRIVATE_KEY: ${{inputs.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{inputs.SSH_KNOWN_HOSTS}}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: 'Setup OpenMDAO pixi Environment'
      id: setup_pixi_environment
      uses: OpenMDAO/OpenMDAO/.github/actions/setup_openmdao_pixi@master
      with:
        environment: '${{ inputs.OPENMDAO_PIXI_ENVIRONMENT }}'
        openmdao_install_from: '${{ inputs.OPENMDAO_INSTALL_FROM }}'
        openmdao_version: '${{ inputs.OPENMDAO }}'

    - name: Install SNOPT
      if: inputs.SNOPT_LOCATION_77
      shell: bash -l {0}
      run: |
        eval "$(pixi shell-hook -e ${{ inputs.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
        echo "============================================================="
        echo "Install SNOPT"
        echo "============================================================="
        if [[ "${{ inputs.SNOPT }}" == "7.7" && "${{ inputs.SNOPT_LOCATION_77 }}" ]]; then
          mkdir SNOPT
          echo "  > Secure copying SNOPT 7.7 over SSH"
          scp -qr ${{ inputs.SNOPT_LOCATION_77 }} SNOPT
          python -m build_pyoptsparse.snopt_module SNOPT/src
        elif [[ "${{ inputs.SNOPT }}" ]]; then
          echo "SNOPT version ${{ inputs.SNOPT }} was requested but source is not available"
        fi

    - name: Install Dymos
      if: inputs.DYMOS
      shell: bash -l {0}
      run: |
        eval "$(pixi shell-hook -e ${{ inputs.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
        echo "============================================================="
        echo "Install Dymos"
        echo "============================================================="
        if [[ "${{ inputs.DYMOS }}" == "dev" ]]; then
          pip install git+https://github.com/OpenMDAO/Dymos
        elif [[ "${{ inputs.DYMOS }}" == "latest" ]]; then
          pip install dymos
        else
          pip install dymos==${{ inputs.DYMOS }}
        fi

    - name: Install Aviary
      shell: bash -l {0}
      run: |
        eval "$(pixi shell-hook -e ${{ inputs.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
        echo "============================================================="
        echo "Install Aviary"
        echo "============================================================="
        pip install -e .[all]

    - name: Check MPI and PETSc
      shell: bash -l {0}
      continue-on-error: true
      run: |
        eval "$(pixi shell-hook -e ${{ inputs.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
        if python -c "import mpi4py, petsc4py" 2>/dev/null; then
          echo "============================================================="
          echo "Check MPI and PETSc installation"
          echo "============================================================="
          export PRTE_MCA_rmaps_default_mapping_policy=:oversubscribe
          export OMPI_MCA_rmaps_base_oversubscribe=1
          export OMPI_MCA_btl=^openib
          echo "-----------------------"
          echo "Quick test of mpi4py:"
          mpirun -n 3 python -c "from mpi4py import MPI; print(f'Rank: {MPI.COMM_WORLD.rank}')"
          echo "-----------------------"
          echo "Quick test of petsc4py:"
          mpirun -n 3 python -c "import numpy; from mpi4py import MPI; comm = MPI.COMM_WORLD; \
            import petsc4py; petsc4py.init(); \
            x = petsc4py.PETSc.Vec().createWithArray(numpy.ones(5)*comm.rank, comm=comm);  \
            print(x.getArray())"
          echo "-----------------------"

          # shellcheck disable=SC2129
          echo "PRTE_MCA_rmaps_default_mapping_policy=:oversubscribe" >> "$GITHUB_ENV"
          echo "OMPI_MCA_rmaps_base_oversubscribe=1" >> "$GITHUB_ENV"
          echo "OMPI_MCA_btl=^openib" >> "$GITHUB_ENV"

          echo "Workaround for intermittent failures with OMPI https://github.com/open-mpi/ompi/issues/7393"
          echo "TMPDIR=/tmp" >> "$GITHUB_ENV"
        else
          echo "mpi4py or petsc4py not installed in this environment, skipping MPI checks"
        fi
