phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.0, "unitless"),
            "final_mach": (0.5, "unitless"),
            "mach_bounds": ((-0.02, 0.52), "unitless"),
            "initial_altitude": (0.0, "ft"),
            "final_altitude": (34500.0, "ft"),
            "altitude_bounds": ((0.0, 35000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": True,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0.0, 0.0), "min"),
            "duration_bounds": ((39.5, 118.5), "min"),
        },
        "initial_guesses": {"time": ([0, 79], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.5, "unitless"),
            "final_mach": (0.5, "unitless"),
            "mach_bounds": ((0.48, 0.52), "unitless"),
            "initial_altitude": (34500.0, "ft"),
            "final_altitude": (70500.0, "ft"),
            "altitude_bounds": ((34000.0, 71000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((39.5, 118.5), "min"),
            "duration_bounds": ((69.0, 207.0), "min"),
        },
        "initial_guesses": {"time": ([79, 138], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.5, "unitless"),
            "final_mach": (0.5, "unitless"),
            "mach_bounds": ((0.48, 0.52), "unitless"),
            "initial_altitude": (70500.0, "ft"),
            "final_altitude": (28000.0, "ft"),
            "altitude_bounds": ((27500.0, 71000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((108.5, 325.5), "min"),
            "duration_bounds": ((35.5, 106.5), "min"),
        },
        "initial_guesses": {"time": ([217, 71], "min")},
    },
    "descent_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.5, "unitless"),
            "final_mach": (0.5, "unitless"),
            "mach_bounds": ((0.48, 0.52), "unitless"),
            "initial_altitude": (28000.0, "ft"),
            "final_altitude": (9500.0, "ft"),
            "altitude_bounds": ((9000.0, 28500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((144.0, 432.0), "min"),
            "duration_bounds": ((16.5, 49.5), "min"),
        },
        "initial_guesses": {"time": ([288, 33], "min")},
    },
    "descent_3": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.5, "unitless"),
            "final_mach": (0.16, "unitless"),
            "mach_bounds": ((0.14, 0.52), "unitless"),
            "initial_altitude": (9500.0, "ft"),
            "final_altitude": (9000.0, "ft"),
            "altitude_bounds": ((8500.0, 10000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((160.5, 481.5), "min"),
            "duration_bounds": ((18.5, 55.5), "min"),
        },
        "initial_guesses": {"time": ([321, 37], "min")},
    },
    "climb_3": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.16, "unitless"),
            "final_mach": (0.78, "unitless"),
            "mach_bounds": ((0.14, 0.8), "unitless"),
            "initial_altitude": (9000.0, "ft"),
            "final_altitude": (25000.0, "ft"),
            "altitude_bounds": ((8500.0, 25500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((179.0, 537.0), "min"),
            "duration_bounds": ((4.5, 13.5), "min"),
        },
        "initial_guesses": {"time": ([358, 9], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.78, "unitless"),
            "final_mach": (0.5, "unitless"),
            "mach_bounds": ((0.48, 0.8), "unitless"),
            "initial_altitude": (25000.0, "ft"),
            "final_altitude": (25000.0, "ft"),
            "altitude_bounds": ((24500.0, 25500.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((183.5, 550.5), "min"),
            "duration_bounds": ((8.5, 25.5), "min"),
        },
        "initial_guesses": {"time": ([367, 17], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (1868, "nmi"),
    },
}
