phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": True,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.0, "unitless"),
            "final_mach": (0.5, "unitless"),
            "mach_bounds": ((-0.02, 0.52), "unitless"),
            "initial_altitude": (0.0, "ft"),
            "final_altitude": (35500.0, "ft"),
            "altitude_bounds": ((0.0, 36000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": True,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0.0, 0.0), "min"),
            "duration_bounds": ((45.5, 136.5), "min"),
        },
        "initial_guesses": {"time": ([0, 91], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": True,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.5, "unitless"),
            "final_mach": (0.5, "unitless"),
            "mach_bounds": ((0.48, 0.52), "unitless"),
            "initial_altitude": (35500.0, "ft"),
            "final_altitude": (37000.0, "ft"),
            "altitude_bounds": ((35000.0, 37500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((45.5, 136.5), "min"),
            "duration_bounds": ((127.5, 382.5), "min"),
        },
        "initial_guesses": {"time": ([91, 255], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": True,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.5, "unitless"),
            "final_mach": (0.5, "unitless"),
            "mach_bounds": ((0.48, 0.52), "unitless"),
            "initial_altitude": (37000.0, "ft"),
            "final_altitude": (1500.0, "ft"),
            "altitude_bounds": ((1000.0, 37500.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((173.0, 519.0), "min"),
            "duration_bounds": ((20.5, 61.5), "min"),
        },
        "initial_guesses": {"time": ([346, 41], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (1897, "nmi"),
    },
}
