name: Bug Report
description: Please submit a report only if you believe you've found a bug in Aviary. If you're not sure your problem is a bug, especially for installation issues, try reaching out on the discussions page first.
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain what is happening and how it differs from the expected behavior.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: Provide a complete, minimal test case that reproduces the issue. Alternatively, link to a file in another repository where the issue is demonstrated.
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Error Message
      description: Provide the full error message, ideally from your code example provided above.
      placeholder: "<< Full traceback starting from `Traceback ..` >>"
    validations:
      required: true
  - type: input
    id: aviary-version
    attributes:
      label: Aviary Version
      description: What version of Aviary is being used?
      placeholder: "0.10.0-dev"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Provide versions of relevant dependencies (openmdao, dymos, numpy, etc). This can be obtained using `pip freeze` or `conda list --export`.
