name: Documentation Request
description: Suggest an improvement or explain issues with the documentation. Errors in code embedded in doc pages should be filed as a bug report.
labels: ["documentation", "request"]
body:
  - type: textarea
    id: desired
    attributes:
      label: Missing documentation or idea for new documentation.
      description: Explain what topic you would like documented, including any specific things you would like addressed in the content.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Issue with existing documentation.
      description: Provide a link to the documentation and explain what you would like to see changed.
    validations:
      required: false
