name: Feature or Change Request
description: Request a new capability or change to an existing feature in Aviary.
labels: ["request"]
body:
  - type: textarea
    id: desired
    attributes:
      label: Desired capability or behavior.
      description: Please explain what changes you would like to see in Aviary.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Suggested implementation.
      description: If you have a suggested solution, describe it below. This could be code or pseudocode, an example of an api change, or a general explanation of your proposed solution.
    validations:
      required: true
