from aviary.variable_info.enums import SpeedType


# 2DOF
phase_info = {
    'groundroll': {
        'subsystem_options': {'core_aerodynamics': {'method': 'low_speed'}},
        'user_options': {
            'num_segments': 1,
            'order': 3,
            'time_initial': (0.0, 's'),
            'time_duration_ref': (50.0, 's'),
            'time_duration_bounds': ((1.0, 50.0), 's'),
            'velocity_initial': (0.066, 'kn'),
            'velocity_bounds': ((0, 150), 'kn'),
            'velocity_ref': (100, 'kn'),
            'mass_bounds': ((0, None), 'lbm'),
            'mass_ref': (150_000, 'lbm'),
            'mass_defect_ref': (150_000, 'lbm'),
            'distance_initial': (0.0, 'ft'),
            'distance_bounds': ((0, 7000), 'ft'),
            'distance_ref': (3500, 'ft'),
            'distance_defect_ref': (3000, 'ft'),
        },
        'initial_guesses': {
            'time': ([0.0, 31.0], 's'),
            'velocity': ([0.066, 120.9], 'kn'),
            'distance': ([0.0, 3500.0], 'ft'),
            'throttle': ([0.956, 0.956], 'unitless'),
        },
    },
    'rotation': {
        'subsystem_options': {'core_aerodynamics': {'method': 'low_speed'}},
        'user_options': {
            'num_segments': 1,
            'order': 3,
            'time_duration_bounds': ((1, 50), 's'),
            'time_duration_ref': (50.0, 's'),
            'velocity_bounds': ((0, 150), 'kn'),
            'velocity_ref': (50, 'kn'),
            'mass_bounds': ((0, None), 'lbm'),
            'mass_ref': (150_000, 'lbm'),
            'mass_defect_ref': (150_000, 'lbm'),
            'distance_bounds': ((0, 5000), 'ft'),
            'distance_ref': (5000, 'ft'),
            'distance_defect_ref': (5000, 'ft'),
            'angle_of_attack_initial': (0.0, 'deg'),
            'angle_of_attack_bounds': ((0.0, 12.0), 'deg'),
            'angle_of_attack_ref': (12.0, 'deg'),
            'normal_ref': (10000, 'lbf'),
        },
        'initial_guesses': {
            'time': ([32.0, 34.0], 's'),
            'angle_of_attack': ([0.0, 10.0], 'deg'),
            'velocity': ([127, 134.0], 'kn'),
            'distance': ([3618.9, 4060.4], 'ft'),
            'throttle': ([0.956, 0.956], 'unitless'),
        },
    },
    'ascent': {
        'subsystem_options': {'core_aerodynamics': {'method': 'low_speed'}},
        'user_options': {
            'num_segments': 4,
            'order': 3,
            'velocity_bounds': ((0, 300), 'kn'),
            'velocity_ref': (200, 'kn'),
            'mass_bounds': ((0, None), 'lbm'),
            'mass_ref': (150_000, 'lbm'),
            'mass_defect_ref': (150_000, 'lbm'),
            'distance_bounds': ((50, 10_000), 'ft'),
            'distance_ref': (1e4, 'ft'),
            'distance_defect_ref': (1e4, 'ft'),
            'altitude_bounds': ((0.0, 500.0), 'ft'),
            'altitude_ref': (500, 'ft'),
            'altitude_defect_ref': (500, 'ft'),
            'altitude_initial': (0, 'ft'),
            'altitude_final': (500, 'ft'),
            'altitude_constraint_ref': (500, 'ft'),
            'flight_path_angle_bounds': ((0.0, 13.0), 'deg'),
            'flight_path_angle_ref': (10.0, 'deg'),
            'flight_path_angle_defect_ref': (10.0, 'deg'),
            'flight_path_angle_initial': (0.0, 'deg'),
            'pitch_constraint_bounds': ((0.0, 15.0), 'deg'),
            'pitch_constraint_ref': (15.0, 'deg'),
        },
        'initial_guesses': {
            'time': ([45.0, 25.0], 's'),
            'flight_path_angle': ([0.0, 8.0], 'deg'),
            'angle_of_attack': ([2.5, 1.5], 'deg'),
            'velocity': ([150.0, 185.0], 'kn'),
            'distance': ([4.0e3, 10.0e3], 'ft'),
            'altitude': ([0.0, 500.0], 'ft'),
            'tau_gear': (0.2, 'unitless'),
            'tau_flaps': (0.9, 'unitless'),
            'throttle': ([0.956, 0.956], 'unitless'),
        },
    },
    'accel': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise'}},
        'user_options': {
            'num_segments': 1,
            'order': 3,
            'alt': (500, 'ft'),
            'EAS_constraint_eq': (250, 'kn'),
            'time_duration_bounds': ((5, 200), 's'),
            'time_duration_ref': (200, 's'),
            'velocity_bounds': ((150, 270), 'kn'),
            'velocity_ref': (270, 'kn'),
            'velocity_ref0': (150, 'kn'),
            'mass_bounds': ((0, None), 'lbm'),
            'mass_ref': (150_000, 'lbm'),
            'distance_bounds': ((1, 150.0), 'NM'),
            'distance_ref': (5, 'NM'),
            'distance_defect_ref': (5, 'NM'),
        },
        'initial_guesses': {
            'time': ([70.0, 13.0], 's'),
            'velocity': ([185.0, 250.0], 'kn'),
            'distance': ([10.0e3, 20.0e3], 'ft'),
            'throttle': ([0.956, 0.956], 'unitless'),
        },
    },
    'climb1': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise'}},
        'user_options': {
            'num_segments': 2,
            'order': 3,
            'EAS_target': (250, 'kn'),
            'mach_cruise': 0.8,
            'target_mach': False,
            'time_duration_bounds': ((100, 1000), 's'),
            'time_duration_ref': (200, 's'),
            'altitude_initial': (500.0, 'ft'),
            'altitude_final': (10.0e3, 'ft'),
            'altitude_bounds': ((500.0, 10_000.0), 'ft'),
            'altitude_ref': (10.0e3, 'ft'),
            'mass_bounds': ((0, None), 'lbm'),
            'mass_ref': (150_000, 'lbm'),
            'distance_bounds': ((0, 100.0), 'NM'),
            'distance_ref': (20, 'NM'),
        },
        'initial_guesses': {
            'time': ([11.0, 15.0], 'min'),
            'distance': ([18.0e3, 105.0e3], 'ft'),
            'altitude': ([500.0, 10.0e3], 'ft'),
            'throttle': ([0.956, 0.956], 'unitless'),
        },
    },
    'climb2': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise'}},
        'user_options': {
            'num_segments': 3,
            'order': 3,
            'EAS_target': (270, 'kn'),
            'mach_cruise': 0.8,
            'target_mach': True,
            'required_available_climb_rate': (0.1, 'ft/min'),
            'time_duration_bounds': ((200, 12_000), 's'),
            'time_duration_ref': (4000, 's'),
            'altitude_final': (41_000, 'ft'),
            'altitude_bounds': ((9000.0, 42_000.0), 'ft'),
            'altitude_ref': (41_000, 'ft'),
            'mass_bounds': ((0, None), 'lbm'),
            'mass_ref': (150_000, 'lbm'),
            'mass_defect_ref': (150_000, 'lbm'),
            'distance_bounds': ((10.0, 1000.0), 'NM'),
            'distance_ref': (500, 'NM'),
        },
        'initial_guesses': {
            'time': ([216.0, 1300.0], 's'),
            'distance': ([100.0e3, 200.0e3], 'ft'),
            'altitude': ([10_000, 20_000], 'ft'),
            'throttle': ([0.956, 0.956], 'unitless'),
        },
    },
    'cruise': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise'}},
        'user_options': {
            'alt_cruise': (41_000, 'ft'),
            'mach_cruise': 0.8,
        },
        'initial_guesses': {
            # [Initial mass, delta mass] for special cruise phase.
            'mass': ([140_000.0, -35_000], 'lbm'),
            'initial_distance': (100.0e3, 'ft'),
            'initial_time': (1_000.0, 's'),
            'altitude': (41_000, 'ft'),
            'mach': (0.8, 'unitless'),
        },
    },
    'desc1': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise'}},
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'EAS_limit': (160, 'kn'),
            'mach_cruise': 0.8,
            'input_speed_type': SpeedType.MACH,
            'time_duration_bounds': ((300.0, 2200.0), 's'),
            'time_duration_ref': (2000, 's'),
            'altitude_final': (10_000, 'ft'),
            'altitude_bounds': ((9000.0, 41_000.0), 'ft'),
            'altitude_ref': (41_000, 'ft'),
            'altitude_constraint_ref': (10000, 'ft'),
            'mass_bounds': ((0, None), 'lbm'),
            'mass_ref': (140_000, 'lbm'),
            'mass_defect_ref': (140_000, 'lbm'),
            'distance_bounds': ((1_000.0, 3_500.0), 'NM'),
            'distance_ref': (3_000, 'NM'),
            'distance_defect_ref': (100, 'NM'),
        },
        'initial_guesses': {
            'mass': (136000.0, 'lbm'),
            'altitude': ([41_000, 10_000], 'ft'),
            'throttle': ([0.0, 0.0], 'unitless'),
            'distance': ([0.92 * 3500, 0.96 * 3500], 'NM'),
            'time': ([28000.0, 500.0], 's'),
        },
    },
    'desc2': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise'}},
        'user_options': {
            'num_segments': 1,
            'order': 7,
            'EAS_limit': (250, 'kn'),
            'mach_cruise': 0.80,
            'input_speed_type': SpeedType.EAS,
            'time_duration_bounds': ((100.0, 5000), 's'),
            'time_duration_ref': (500, 's'),
            'altitude_final': (1000, 'ft'),
            'altitude_bounds': ((500.0, 11_000.0), 'ft'),
            'altitude_ref': (10.0e3, 'ft'),
            'altitude_ref0': (1000, 'ft'),
            'altitude_constraint_ref': (1000, 'ft'),
            'mass_bounds': ((0, None), 'lbm'),
            'mass_ref': (150_000, 'lbm'),
            'mass_defect_ref': (150_000, 'lbm'),
            'distance_bounds': ((3000.0, 5000.0), 'NM'),
            'distance_ref': (3500, 'NM'),
            'distance_defect_ref': (100, 'NM'),
        },
        'initial_guesses': {
            'mass': (136000.0, 'lbm'),
            'altitude': ([10.0e3, 1.0e3], 'ft'),
            'throttle': ([0.0, 0.0], 'unitless'),
            'distance': ([0.96 * 3500, 3500], 'NM'),
            'time': ([28500.0, 500.0], 's'),
        },
    },
    'post_mission': {
        #'constrain_range': True,
        #'target_range': (3000.0, 'nmi'),
    },
}
