phase_info = {
    'pre_mission': {'include_takeoff': False, 'optimize_mass': False},
    'GH': {
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'ground_roll': False,
            'clean': False,
            'time_initial': (0.0, 'ft'),
            'time_duration_ref': (2750.0, 'ft'),
            'time_duration_bounds': ((500.0, 5.0e3), 'ft'),
            'mach_optimize': False,
            'mach_polynomial_order': 1,
            'mach_bounds': ((0.1, 0.5), 'unitless'),
            'mach_initial': (0.15, 'unitless'),
            'mach_final': (0.15, 'unitless'),
            'altitude_optimize': False,
            'altitude_polynomial_order': 1,
            'altitude_initial': (500.0, 'ft'),
            'altitude_final': (394.0, 'ft'),
            'altitude_bounds': ((0.0, 1000.0), 'ft'),
            'mass_initial': (120.0e3, 'lbm'),
            'mass_ref': (120.0e3, 'lbm'),
            'mass_bounds': ((0.0, 200.0e3), 'lbm'),
            'throttle_enforcement': 'path_constraint',
            'rotation': False,
            'constraints': {
                'flight_path_angle': {
                    'equals': -3.0,
                    'loc': 'initial',
                    'units': 'deg',
                    'type': 'boundary',
                },
            },
        },
        'initial_guesses': {
            'distance': [(0.0e3, 2.0e3), 'ft'],
            'time': [(0.0, 12.0), 's'],
            'mass': [(120.0e3, 119.8e3), 'lbm'],
        },
    },
    'HI': {
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'ground_roll': False,
            'clean': False,
            'time_initial_ref': (1.0e3, 'ft'),
            'time_initial_bounds': ((0.0, 16.0e3), 'ft'),
            'time_duration_ref': (1.0e3, 'ft'),
            'time_duration_bounds': ((500.0, 15.0e3), 'ft'),
            'mach_optimize': False,
            'mach_polynomial_order': 1,
            'mach_initial': (0.15, 'unitless'),
            'mach_final': (0.15, 'unitless'),
            'mach_bounds': ((0.1, 0.5), 'unitless'),
            'altitude_optimize': False,
            'altitude_polynomial_order': 1,
            'altitude_initial': (394.0, 'ft'),
            'altitude_final': (50.0, 'ft'),
            'altitude_bounds': ((0.0, 1000.0), 'ft'),
            'mass_ref': (120.0e3, 'lbm'),
            'mass_bounds': ((0.0, 200.0e3), 'lbm'),
            'throttle_enforcement': 'path_constraint',
            'rotation': False,
            'constraints': {
                'flight_path_angle': {
                    'equals': -3.0,
                    'loc': 'final',
                    'units': 'deg',
                    'type': 'boundary',
                },
            },
        },
        'initial_guesses': {
            'distance': [(2.0e3, 6.5e3), 'ft'],
            'time': [(12.0, 50.0), 's'],
            'mass': [(119.8e3, 119.7e3), 'lbm'],
        },
    },
    'IJ': {
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'ground_roll': False,
            'clean': False,
            'time_initial_ref': (1.0e3, 'ft'),
            'time_initial_bounds': ((0.0, 30.0e3), 'ft'),
            'time_duration_ref': (1.0e3, 'ft'),
            'time_duration_bounds': ((500.0, 15.0e3), 'ft'),
            'mach_optimize': False,
            'mach_polynomial_order': 2,
            'mach_bounds': ((0.1, 0.5), 'unitless'),
            'mach_initial': (0.15, 'unitless'),
            'mach_final': (0.15, 'unitless'),
            'altitude_optimize': True,
            'altitude_polynomial_order': 2,
            'altitude_final': (0.0, 'ft'),
            'altitude_bounds': ((0.0, 1000.0), 'ft'),
            'mass_ref': (120.0e3, 'lbm'),
            'mass_bounds': ((0.0, 200.0e3), 'lbm'),
            'throttle_enforcement': 'path_constraint',
            'rotation': False,
            'constraints': {},
        },
        'initial_guesses': {
            'altitude': [(50.0, 0.0), 'ft'],
            'distance': [(8.5e3, 2.0e3), 'ft'],
            'time': [(50.0, 60.0), 's'],
            'mass': [(119.7e3, 119.67e3), 'lbm'],
        },
    },
    'post_mission': {
        'include_landing': False,
        'constrain_range': False,
    },
}
