phase_info = {
    'pre_mission': {'include_takeoff': False,  'optimize_mass': False},
    'climb': {
        'subsystem_options': {'core_aerodynamics': {'method': 'computed'}},
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'mach_optimize': True,
            'mach_polynomial_order': 3,
            'mach_initial': (0.04, 'unitless'),
            # 'mach_final': (0., 'unitless'),
            'altitude_optimize': False,
            'altitude_polynomial_order': 3,
            'altitude_initial': (0.0, 'ft'),
            'altitude_final': (200.0, 'ft'),
            'throttle_enforcement': 'path_constraint',
            'time_initial': (0.0, 'min'),
            'time_duration_bounds': ((1, 40), 's'),
        },
        'initial_guesses': {
            'time': ([0, 15], 's'),
            'mach': ([0.04, 0.04], 'unitless')
        },
    },
    'cruise': {
        'subsystem_options': {'core_aerodynamics': {'method': 'computed'}},
        'user_options': {
            'num_segments': 1,
            'order': 3,
            'mach_optimize': False,
            'mach_polynomial_order': 1,
            'mach_initial': (0.031, 'unitless'),
            'mach_final': (0.031, 'unitless'),
            'altitude_optimize': False,
            'altitude_polynomial_order': 1,
            'altitude_initial': (200, 'ft'),
            'altitude_final': (200, 'ft'),
            'throttle_enforcement': 'boundary_constraint',
            'time_initial_bounds': ((0, 20), 's'),
            'time_duration_bounds': ((1, 100), 's'),
        },
        'initial_guesses': {
            'time': ([1, 100], 's'),
        },
    },
    'descent': {
        'subsystem_options': {'core_aerodynamics': {'method': 'computed'}},
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'mach_optimize': False,
            'mach_polynomial_order': 1,
            'mach_initial': (0.72, 'unitless'),
            'mach_final': (0.36, 'unitless'),
            'altitude_optimize': False,
            'altitude_polynomial_order': 1,
            'altitude_initial': (34000.0, 'ft'),
            'altitude_final': (500.0, 'ft'),
            'throttle_enforcement': 'path_constraint',
            'time_initial_bounds': ((120.5, 361.5), 'min'),
            'time_duration_bounds': ((29.0, 87.0), 'min'),
        },
        'initial_guesses': {'time': ([241, 58], 'min')},
    },
    'post_mission': {
        'include_landing': False,
        # 'target_range': (200, 'ft'),
        'constraint_range':True, 
    },
}
