phase_info = {
    'pre_mission': {'include_takeoff': True, 'optimize_mass': True},
    'climb': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise', 'solve_alpha': True}},
        'user_options': {
            'num_segments': 6,
            'order': 3,
            'mach_optimize': True,
            'mach_bounds': ((0.1, 0.8), 'unitless'),
            'altitude_optimize': True,
            'altitude_bounds': ((0.0, 36000.0), 'ft'),
            'throttle_enforcement': 'path_constraint',
            'time_initial_bounds': ((0.0, 0.0), 'min'),
            'time_duration_bounds': ((5.0, 50.0), 'min'),
            'no_descent': True,
        },
        'initial_guesses': {
            'time': ([0, 40.0], 'min'),
            'altitude': ([0, 35000.0], 'ft'),
            'mach': ([0.2, 0.79], 'unitless'),
        },
    },
    'cruise': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise', 'solve_alpha': True}},
        'user_options': {
            'num_segments': 1,
            'order': 3,
            'mach_optimize': True,
            'mach_polynomial_order': 1,
            'mach_initial': (0.79, 'unitless'),
            'mach_bounds': ((0.78, 0.8), 'unitless'),
            'altitude_optimize': True,
            'altitude_polynomial_order': 1,
            'altitude_initial': (35000.0, 'ft'),
            'altitude_bounds': ((35000.0, 35000.0), 'ft'),
            'throttle_enforcement': 'boundary_constraint',
            'time_initial_bounds': ((64.0, 192.0), 'min'),
            'time_duration_bounds': ((60.0, 7200.0), 'min'),
        },
        'initial_guesses': {
            'time': ([128, 113], 'min'),
            'altitude': ([35000, 35000.0], 'ft'),
            'mach': ([0.79, 0.79], 'unitless'),
        },
    },
    'descent': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise', 'solve_alpha': True}},
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'mach_optimize': True,
            'mach_initial': (0.79, 'unitless'),
            'mach_final': (0.3, 'unitless'),
            'mach_bounds': ((0.2, 0.8), 'unitless'),
            'altitude_optimize': True,
            'altitude_initial': (35000.0, 'ft'),
            'altitude_final': (500.0, 'ft'),
            'altitude_bounds': ((0.0, 35000.0), 'ft'),
            'throttle_enforcement': 'path_constraint',
            'time_initial_bounds': ((120.5, 361.5), 'min'),
            'time_duration_bounds': ((5.0, 30.0), 'min'),
            'no_climb': True,
        },
        'initial_guesses': {'time': ([241, 30], 'min')},
    },
    'post_mission': {
        'include_landing': False,
        'constrain_range': True,
        'target_range': (3360.0, 'nmi'),
    },
}
