phase_info = {
    'pre_mission': {'include_takeoff': False, 'optimize_mass': True},
    'climb': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise', 'solve_alpha': True}},
        'user_options': {
            'fix_initial': True,
            'input_initial': False,
            'optimize_mach': True,
            'optimize_altitude': True,
            'use_polynomial_control': False,
            'num_segments': 6,
            'order': 3,
            'solve_for_distance': False,
            'initial_mach': (0.3, 'unitless'),
            'final_mach': (0.79, 'unitless'),
            'mach_bounds': ((0.3, 0.79), 'unitless'),
            'initial_altitude': (35.0, 'ft'),
            'final_altitude': (35000.0, 'ft'),
            'altitude_bounds': ((0.0, 35000.0), 'ft'),
            'throttle_enforcement': 'path_constraint',
            'constrain_final': False,
            'fix_duration': False,
            'initial_bounds': ((0.0, 0.0), 'min'),
            'duration_bounds': ((5.0, 50.0), 'min'),
            'no_descent': True,
            'add_initial_mass_constraint': False,
        },
        'initial_guesses': {'time': ([0, 30.0], 'min')},
    },
    'cruise': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise', 'solve_alpha': True}},
        'user_options': {
            'optimize_mach': True,
            'optimize_altitude': True,
            'polynomial_control_order': 1,
            'use_polynomial_control': True,
            'num_segments': 1,
            'order': 3,
            'solve_for_distance': False,
            'initial_mach': (0.79, 'unitless'),
            'final_mach': (0.79, 'unitless'),
            'mach_bounds': ((0.78, 0.8), 'unitless'),
            'initial_altitude': (35000.0, 'ft'),
            'final_altitude': (35000.0, 'ft'),
            'altitude_bounds': ((35000.0, 35000.0), 'ft'),
            'throttle_enforcement': 'boundary_constraint',
            'fix_initial': False,
            'constrain_final': False,
            'fix_duration': False,
            'initial_bounds': ((5.0, 50.0), 'min'),
            'duration_bounds': ((120.0, 720.0), 'min'),
        },
        'initial_guesses': {'time': ([30, 490], 'min')},
    },
    'descent': {
        'subsystem_options': {'core_aerodynamics': {'method': 'cruise', 'solve_alpha': True}},
        'user_options': {
            'optimize_mach': True,
            'optimize_altitude': True,
            'use_polynomial_control': False,
            'num_segments': 5,
            'order': 3,
            'solve_for_distance': False,
            'initial_mach': (0.79, 'unitless'),
            'final_mach': (0.3, 'unitless'),
            'mach_bounds': ((0.3, 0.79), 'unitless'),
            'initial_altitude': (35000.0, 'ft'),
            'final_altitude': (500.0, 'ft'),
            'altitude_bounds': ((0.0, 35000.0), 'ft'),
            'throttle_enforcement': 'path_constraint',
            'fix_initial': False,
            'constrain_final': True,
            'fix_duration': False,
            'initial_bounds': ((170, 800.0), 'min'),
            'duration_bounds': ((5.0, 75.0), 'min'),
            'no_climb': True,
        },
        'initial_guesses': {'time': ([520, 45], 'min')},
    },
    'post_mission': {
        'include_landing': False,
        'constrain_range': True,
        'target_range': (3360.0, 'nmi'),
    },
}
