from aviary.utils.named_values import NamedValues

## Defaults ##
# commented out values were not in metadata at the time
gasp_default_values = NamedValues(
    {
        'INGASP.ALTLND': (0, 'ft'),
        'INGASP.ARNGE(1)': (0, 'NM'),  # Aviary reads ARNGE(1) only. ARNGE(2) - ARNGE(4) are ignored
        'INGASP.AS': (1, 'unitless'),  # GASP does not have a default but 1 is reasonable
        'INGASP.BOELTV': (0, 'unitless'),
        'INGASP.BTEOB': (0.75, 'unitless'),
        'INGASP.CFOC': (0.3, 'unitless'),
        'INGASP.CK5': (1.0, 'unitless'),
        # 'INGASP.CK7': (1.0, 'unitless'),
        # 'INGASP.CK8': (1.0, 'unitless'),
        # 'INGASP.CK9': (1.0, 'unitless'),
        # 'INGASP.CK10': (1.0, 'unitless'),
        # 'INGASP.CK11': (1.0, 'unitless'),
        'INGASP.CK12': (1.0, 'unitless'),
        'INGASP.CK14': (1.0, 'unitless'),
        'INGASP.CK15': (1.0, 'unitless'),
        # 'INGASP.CK18': (1.0, 'unitless'),
        'INGASP.CK19': (1.0, 'unitless'),
        'INGASP.CK21': (1.0, 'unitless'),
        'INGASP.CKF': (-1.0, 'unitless'),
        'INGASP.CKFF': (1.0, 'unitless'),
        'INGASP.CKHT': (-1.0, 'unitless'),
        'INGASP.CKI': (0.0, 'unitless'),
        'INGASP.CKN': (-1.0, 'unitless'),
        'INGASP.CKSTRT': (1.0, 'unitless'),
        'INGASP.CKVT': (-1.0, 'unitless'),
        'INGASP.CKW': (-1.0, 'unitless'),
        'INGASP.CLEARqDN': (0.2, 'unitless'),
        'INGASP.CLEOC': (0.0, 'unitless'),
        'INGASP.COELTH': (0.0, 'unitless'),
        'INGASP.CRALT': (0.0, 'ft'),
        'INGASP.CRMACH': (0.0, 'unitless'),
        'INGASP.CW(1)': (0.0, 'lbm'),
        'INGASP.CW(2)': (0.0862, 'unitless'),
        'INGASP.CW(3)': (0.1, 'unitless'),
        'INGASP.CW(4)': (0.16, 'unitless'),
        'INGASP.CW(5)': (0.0, 'lbm'),
        'INGASP.CW(6)': (1.0, 'unitless'),
        'INGASP.CW(7)': (0.0, 'lbm'),
        'INGASP.CW(8)': (0.0, 'lbm'),
        'INGASP.CW(9)': (2.0, 'lbm'),
        'INGASP.CW(10)': (1.0, 'lbm'),
        'INGASP.CW(11)': (0.0, 'lbm'),
        'INGASP.CW(12)': (0.7, 'lbm'),
        'INGASP.CW(13)': (6.0, 'unitless'),
        'INGASP.CW(14)': (0.0, 'lbm'),
        'INGASP.CW(15)': (16.0, 'lbm'),
        'INGASP.CW(16)': (0.0, 'unitless'),
        'INGASP.DCDOTE': (0.0, 'unitless'),
        'INGASP.DCLMLE': (0.93, 'unitless'),
        'INGASP.DCLMTE': (0.0, 'unitless'),
        'INGASP.DELCD': (0.0015, 'unitless'),
        'INGASP.DELCG': (0.25, 'unitless'),
        'INGASP.DELFE': (0.25, 'ft**2'),
        'INGASP.DELLED': (0.0, 'deg'),
        'INGASP.DELLEO': (45.0, 'deg'),
        'INGASP.DELTEO': (0.0, 'deg'),
        'INGASP.DELTT': (0.1677, 'h'),
        'INGASP.DELWFC': (0.0, 'lbm'),
        'INGASP.DELWST': (0.0, 'lbm'),
        'INGASP.DFLPLD': (40, 'deg'),
        'INGASP.DFLPTO': (10, 'deg'),
        'INGASP.DIAM_REF': (5.8, 'ft'),  # no DIAM_REF in GASP
        'INGASP.DNQDE': (1.0, 'unitless'),
        'INGASP.DV1': (5.0, 'kn'),
        'INGASP.DVR': (5.0, 'kn'),
        'INGASP.DWPQCH': (25.0, 'deg'),
        'INGASP.DWPQCV': (35.0, 'deg'),
        'INGASP.ELODN': (2.0, 'unitless'),
        'INGASP.ELODT': (3.2, 'unitless'),
        'INGASP.ELPC': (4.44, 'ft'),
        'INGASP.ENP': (2, 'unitless'),  # GASP does not have a default but 2 is reasonable
        'INGASP.EYEW': (1.5, 'deg'),
        'INGASP.FLAPN': (1.0, 'unitless'),
        'INGASP.FN_REF': (28690, 'lbf'),  # no FN_REF in GASP
        'INGASP.FPYL': (
            0.0,
            'unitless',
        ),  # in GASP manual, default is 0.7 if NTYE=7 and KNAC=2, but source code is 0.0
        'INGASP.FRESF': (1.0, 'lbm'),
        'INGASP.FUELD': (6.687, 'lbm/galUS'),
        'INGASP.FVOL_MRG': (0.0, 'unitless'),
        'INGASP.HAPP': (50.0, 'ft'),
        'INGASP.HCK': (2.47, 'ft'),
        # 'INGASP.HPORT': (0, 'ft'),
        'INGASP.HTG': (3.0, 'ft'),
        'INGASP.HWING': (0.0, 'unitless'),
        'INGASP.IGEAR': (False, 'unitless'),
        'INGASP.IHWB': ('transport', 'unitless'),
        # 'INGASP.JENGSZ': (4, 'unitless'),
        'INGASP.JFLTYP': ('single_slotted', 'unitless'),
        'INGASP.NTYE': (7, 'unitless'),  # GASP does not have a default but 7 is reasonable
        'INGASP.ROCTOC': (0.0, 'ft/min'),
        'INGASP.RCLMAX': (1.0, 'unitless'),
        'INGASP.RSMX': (1000.0, 'ft/min'),
        'INGASP.SCFAC': (0.0, 'unitless'),
        'INGASP.SF_FAC': (1.0, 'unitless'),
        'INGASP.SINKTD': (3.0, 'ft/s'),
        'INGASP.SKB': (136.0, 'unitless'),
        'INGASP.SKCC': (11, 'unitless'),
        'INGASP.SKFS': (0.0195, 'unitless'),
        'INGASP.SKFW': (0.404, 'unitless'),
        'INGASP.SKLG': (0.0318, 'unitless'),
        'INGASP.SKMG': (0.8, 'unitless'),
        'INGASP.SKPEI': (0.135, 'unitless'),
        'INGASP.SKSAS': (0.0, 'lbm'),
        'INGASP.SKSTRUT': (0.0, 'unitless'),
        'INGASP.SKTL': (1.0, 'unitless'),
        'INGASP.SKWF': (0.43, 'unitless'),
        'INGASP.SKWFOLD': (0.0, 'unitless'),
        'INGASP.SKWW': (133.4, 'unitless'),
        'INGASP.SKY': (0.18, 'unitless'),
        'INGASP.SKZ': (0.22, 'unitless'),
        'INGASP.SSTQSW': (0.0, 'unitless'),
        'INGASP.STATIC': (0.05, 'unitless'),
        'INGASP.STRUT': (0.0, 'ft'),
        'INGASP.SWSLS': (0.0, 'lbm/lbf'),
        'INGASP.TDELAY': (1.0, 's'),
        'INGASP.THIN': (0.0, 'lbf'),
        'INGASP.VBARHX': (0.0, 'unitless'),
        'INGASP.VBARVX': (0.0, 'unitless'),
        'INGASP.VRATT': (1.3, 'unitless'),
        'INGASP.WCARGO': (0.0, 'lbm'),
        'INGASP.WCFLAP': (-1.0, 'unitless'),
        'INGASP.WG': (0.0, 'lbm'),
        'INGASP.WGS': (0.0, 'lbf/ft**2'),
        'INGASP.XCPS': (0.3, 'unitless'),
        'INGASP.XCTCMX': (0.35, 'unitless'),
        'INGASP.XLFMX': (1.2, 'unitless'),
        'INGASP.XLQDE': (3.5, 'unitless'),
        'INGASP.XWQLF': (0.4, 'unitless'),
        'INGASP.YMG': (0.15, 'unitless'),
        'INGASP.YWFOLD': (0.0, 'ft'),
    }
)

## Depreciated Variables ##
gasp_deprecated_vars = []
