# Run Tests

name: Test with Pre-Release OpenMDAO/Dymos

on:

  # Run the workflow every Tuesday at 0400 UTC
  schedule:
    - cron: '1 4 * * 1,4'

  # Allow running the workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel any existing CI runs if we push to this branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test_ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          # latest released version of pyoptsparse
          # development versions of openmdao/dymos
          - NAME: dev
            OS: ubuntu-24.04
            OPENMDAO_PIXI_ENVIRONMENT: 'py313'
            OPENMDAO_INSTALL_FROM: 'github'
            OPENMDAO: ''
            SNOPT: '7.7'
            DYMOS: 'dev'

    runs-on: ${{ matrix.OS }}

    steps:
      - name: Checkout actions
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
          path: actions

      - name: prepare_testing_environment
        uses: ./actions/.github/actions/prepare_environment
        with:
          NAME: ${{ matrix.NAME }}
          OPENMDAO_PIXI_ENVIRONMENT: ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }}
          OPENMDAO_INSTALL_FROM: ${{ matrix.OPENMDAO_INSTALL_FROM }}
          OPENMDAO: ${{ matrix.OPENMDAO }}
          SNOPT: ${{ matrix.SNOPT }}
          DYMOS: ${{ matrix.DYMOS }}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SNOPT_LOCATION_77: ${{ secrets.SNOPT_LOCATION_77 }}

      - name: Run tests
        shell: bash -l {0}
        run: |
          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
          echo "============================================================="
          echo "Run Tests"
          echo "============================================================="
          testflo . --timeout=200 --show_skipped --coverage --coverpkg aviary

      - name: Checkout actions (again)
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
          path: actions

      - name: Send Email on failed tests
        if: failure()
        uses: ./actions/.github/actions/send_email
        with:
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: ${{ secrets.DESTINATION_EMAIL }}
          subject: "***Notification*** Tests failed with development versions of OpenMDAO/Dymos: ${{ github.run_id }}"
          body: |
            {
              "title": "Test with Pre-Release OpenMDAO/Dymos",
              "action": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
